const PROCEDURES = [
  { naam: "PTA ± stentplaatsing beenvaten", categorie: "Vasculair", subcategorie: "Perifeer arterieel", tag: "vasc",
    url: "vasculair/pta-beenvaten.html",
    trefwoorden: ["PTA","angioplastiek","stent","beenvaten","femoropopliteaal","cruraal","claudicatio","ischemie","Fontaine","DEB","nitinol"] },
  { naam: "rTPA opstarten — acuut bedreigd been", categorie: "Vasculair", subcategorie: "Trombolyse", tag: "urgent",
    url: "vasculair/rtpa-trombolyse.html",
    trefwoorden: ["trombolyse","rTPA","alteplase","acuut","bedreigd been","Rutherford","CDT","McNamara","heparine","fibrinogeen"] },
  { naam: "Port-a-cath plaatsing bovenarmport", categorie: "Vasculair", subcategorie: "Vascular access", tag: "vasc",
    url: "vasculair/port-a-cath.html",
    trefwoorden: ["port","port-a-cath","bovenarmport","chemotherapie","veneuze toegang","basilica","cephalica","Huber","peel-away","pocket"] },
  { naam: "Uterusembolisatie bij fluxus", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/uterusembolisatie.html",
    trefwoorden: ["UAE","uterusembolisatie","fluxus","postpartum","hemorragie","spongostan","A. uterina","bloeding","partus","glidecath"] },
  { naam: "Prostaat arterie embolisatie", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/pae.html",
    trefwoorden: ["PAE","prostaat","embolisatie","LUTS","BPH","PVA","Contour","verapamil","conebeam","microkatheter","Tellus","Meister"] },
  { naam: "Percutane nefrostomie", categorie: "Non-vasculair", subcategorie: "Urologie", tag: "nonvasc",
    url: "non-vasculair/nefrostomie.html",
    trefwoorden: ["nefrostomie","nier","hydronefrose","obstructie","urolithiasis","drain","Amplatz","pigtail","ureter","Neffset"] },

  { naam: "Wissel nefrodrain", categorie: "Non-vasculair", subcategorie: "Urologie", tag: "nonvasc",
    url: "non-vasculair/wissel-nefrodrain.html",
    trefwoorden: ["wissel","nefrodrain","nefrostomie","drain","pyelum","Amplatz","katheter","tractus"] },
  { naam: "PTCD galwegdrainage", categorie: "Non-vasculair", subcategorie: "Galwegen", tag: "nonvasc",
    url: "non-vasculair/ptcd.html",
    trefwoorden: ["PTCD","galweg","cholangio","icterus","drainage","obstructie","SEMS","cholangitis","Bismuth","Chiba","TESLA"] },

  { naam: "PICC-lijn plaatsing", categorie: "Vasculair", subcategorie: "Vascular access", tag: "vasc",
    url: "vasculair/picc-lijn.html",
    trefwoorden: ["PICC","lijn","centraal veneus","basilica","brachialis","peel-away","micropunctie","chemotherapie","antibiotica","TPN"] },
  { naam: "Ascitesdrainage", categorie: "Non-vasculair", subcategorie: "Drainage", tag: "nonvasc",
    url: "non-vasculair/ascitesdrainage.html",
    trefwoorden: ["ascites","drainage","buikvocht","lever","cirrose","peritoneaal","epigastrisch","one-step","therapeutisch","diagnostisch"] },
  { naam: "Nierbiopt", categorie: "Non-vasculair", subcategorie: "Biopsie", tag: "nonvasc",
    url: "non-vasculair/nierbiopt.html",
    trefwoorden: ["nierbiopt","biopsie","nier","IgA","nefropathie","FSGS","vasculitis","glomerulonefritis","nefrotisch","nefritisch","16G"] },
  { naam: "Shunt MDO", categorie: "MDO", subcategorie: "Hemodialyse toegang", tag: "vasc",
    url: "mdo/shunt-mdo.html",
    trefwoorden: ["shunt","AVF","AVG","hemodialyse","MDO","fistel","RCAVF","BCAVF","basilica transpositie","duplex"] }
];
