const PROCEDURES = [
  { naam: "PTA ± stentplaatsing beenvaten", categorie: "Vasculair", subcategorie: "Arterieel", tag: "vasc",
    url: "vasculair/pta-beenvaten.html",
    trefwoorden: ["PTA","angioplastiek","stent","beenvaten","femoropopliteaal","cruraal","claudicatio","ischemie","Fontaine","DEB","nitinol"] },
  { naam: "rTPA opstarten — acuut bedreigd been", categorie: "Vasculair", subcategorie: "Arterieel", tag: "urgent",
    url: "vasculair/rtpa-trombolyse.html",
    trefwoorden: ["trombolyse","rTPA","alteplase","acuut","bedreigd been","Rutherford","CDT","McNamara","heparine","fibrinogeen"] },
  { naam: "Port-a-cath plaatsing bovenarmport", categorie: "Vasculair", subcategorie: "Veneuze toegang", tag: "vasc",
    url: "vasculair/port-a-cath.html",
    trefwoorden: ["port","port-a-cath","bovenarmport","chemotherapie","veneuze toegang","basilica","cephalica","Huber","peel-away","pocket"] },
  { naam: "Uterusembolisatie bij fluxus", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/uterusembolisatie.html",
    trefwoorden: ["UAE","uterusembolisatie","fluxus","postpartum","hemorragie","spongostan","A. uterina","bloeding","partus","glidecath"] },
  { naam: "Uterusembolisatie bij myomen/adenomyose", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/uterusembolisatie-electief.html",
    trefwoorden: ["UAE","UFE","uterusembolisatie","myomen","fibroom","fibroid","adenomyose","Contour","partikels","menorragie","A. uterina","Progreat","electief","RIM"] },
  { naam: "Prostaat arterie embolisatie", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/pae.html",
    trefwoorden: ["PAE","prostaat","embolisatie","LUTS","BPH","PVA","Contour","verapamil","conebeam","microkatheter","Tellus","Meister"] },
  { naam: "Percutane nefrostomie", categorie: "Non-vasculair", subcategorie: "Urogenitaal", tag: "nonvasc",
    url: "non-vasculair/nefrostomie.html",
    trefwoorden: ["nefrostomie","nier","hydronefrose","obstructie","urolithiasis","drain","Amplatz","pigtail","ureter","Neffset"] },

  { naam: "Wissel nefrodrain", categorie: "Non-vasculair", subcategorie: "Urogenitaal", tag: "nonvasc",
    url: "non-vasculair/wissel-nefrodrain.html",
    trefwoorden: ["wissel","nefrodrain","nefrostomie","drain","pyelum","Amplatz","katheter","tractus"] },

  { naam: "Sclerosering Morel-Lavallée laesie", categorie: "Non-vasculair", subcategorie: "Overig", tag: "nonvasc",
    url: "non-vasculair/morel-lavallee.html",
    trefwoorden: ["Morel-Lavallée","sclerosering","alcohol","seroom","weke delen","fascie","post-traumatisch","aspiratie","cyste"] },
  { naam: "Sclerosering schildkliercyste", categorie: "Non-vasculair", subcategorie: "Overig", tag: "nonvasc",
    url: "non-vasculair/schildkliercyste.html",
    trefwoorden: ["schildklier","cyste","sclerosering","alcohol","aspiratie","thyroid"] },
  { naam: "PTCD galwegdrainage", categorie: "Non-vasculair", subcategorie: "Lever & galwegen", tag: "nonvasc",
    url: "non-vasculair/ptcd.html",
    trefwoorden: ["PTCD","galweg","cholangio","icterus","drainage","obstructie","SEMS","cholangitis","Bismuth","Chiba","TESLA"] },
  { naam: "Galblaasdrainage (cholecystostomie)", categorie: "Non-vasculair", subcategorie: "Lever & galwegen", tag: "nonvasc",
    url: "non-vasculair/galblaasdrain.html",
    trefwoorden: ["galblaas","cholecystostomie","cholecystitis","cholecystostomy","gallbladder","drain","transhepatisch","empyeem","opspuitfoto","cholangiografie","pigtail"] },

  { naam: "PICC-lijn plaatsing", categorie: "Vasculair", subcategorie: "Veneuze toegang", tag: "vasc",
    url: "vasculair/picc-lijn.html",
    trefwoorden: ["PICC","lijn","centraal veneus","basilica","brachialis","peel-away","micropunctie","chemotherapie","antibiotica","TPN"] },
  { naam: "Ascitesdrainage", categorie: "Non-vasculair", subcategorie: "Drainage", tag: "nonvasc",
    url: "non-vasculair/ascitesdrainage.html",
    trefwoorden: ["ascites","drainage","buikvocht","lever","cirrose","peritoneaal","epigastrisch","one-step","therapeutisch","diagnostisch"] },
  { naam: "Permanente ascitesdrain (IPC)", categorie: "Non-vasculair", subcategorie: "Drainage", tag: "nonvasc",
    url: "non-vasculair/permanente-ascitesdrain.html",
    trefwoorden: ["IPC","ascites","tunnelkatheter","tunneldrain","permanent","peritoneum","Rocket","maligne ascites","peel-away","drain","scuff","indwelling","katheter"] },
  { naam: "Antistolling bij interventies", categorie: "Materiaal", subcategorie: "Referentie", tag: "mat",
    url: "materiaal/antistolling.html",
    trefwoorden: ["antistolling","plaatjesremmer","INR","VKA","DOAC","dabigatran","heparine","LMWH","stollingslab","staken","anticoagulation","bridging"] },
  { naam: "Antegrade JJ-katheter", categorie: "Non-vasculair", subcategorie: "Urogenitaal", tag: "nonvasc",
    url: "non-vasculair/jj-katheter.html",
    trefwoorden: ["JJ","dubbel-J","ureterstent","antegrade","ureter","obstructie","nefrostomie","stent","double-J","ureteric"] },
  { naam: "Percutane radiologische gastrostomie (PRG)", categorie: "Non-vasculair", subcategorie: "Overig", tag: "nonvasc",
    url: "non-vasculair/gastrostomie.html",
    trefwoorden: ["gastrostomie","PRG","PEG","voedingssonde","maag","gastropexie","T-fastener","decompressie","push-type","feeding tube"] },
  { naam: "Percutane abcesdrainage", categorie: "Non-vasculair", subcategorie: "Drainage", tag: "nonvasc",
    url: "non-vasculair/abcesdrainage.html",
    trefwoorden: ["abces","drainage","collectie","Seldinger","trocar","pigtail","empyeem","pus","abscess","fluid collection"] },
  { naam: "Thoraxdrainage / pleurapunctie", categorie: "Non-vasculair", subcategorie: "Drainage", tag: "nonvasc",
    url: "non-vasculair/thoraxdrainage.html",
    trefwoorden: ["thoraxdrainage","pleurapunctie","thoracentese","pleuravocht","empyeem","pneumothorax","Light","exsudaat","transsudaat","pleural","thoracentesis"] },
  { naam: "Stentplaatsing galwegen", categorie: "Non-vasculair", subcategorie: "Lever & galwegen", tag: "nonvasc",
    url: "non-vasculair/biliary-stenting.html",
    trefwoorden: ["biliary","stent","SEMS","galweg","galwegen","obstructie","icterus","cholangiocarcinoom","PTCD","metallic stent","biliary stenting","stentplaatsing galwegen"] },
  { naam: "Leverablatie (RFA/MWA)", categorie: "Oncologie", subcategorie: "Ablatie", tag: "onco",
    url: "oncologie/ablatie-lever.html",
    trefwoorden: ["ablatie","RFA","MWA","radiofrequent","microgolf","lever","HCC","metastase","tumor","thermisch","ablation","microwave"] },
  { naam: "Schildklierablatie (RFA)", categorie: "Non-vasculair", subcategorie: "Overig", tag: "nonvasc",
    url: "non-vasculair/ablatie-schildklier.html",
    trefwoorden: ["schildklier","ablatie","RFA","nodus","thyroid","moving-shot","TI-RADS","benigne","recurrens","thyroid ablation","nodule"] },
  { naam: "Nierbiopt", categorie: "Non-vasculair", subcategorie: "Urogenitaal", tag: "nonvasc",
    url: "non-vasculair/nierbiopt.html",
    trefwoorden: ["nierbiopt","biopsie","nier","IgA","nefropathie","FSGS","vasculitis","glomerulonefritis","nefrotisch","nefritisch","16G"] },
  { naam: "Leverbiopt", categorie: "Non-vasculair", subcategorie: "Lever & galwegen", tag: "nonvasc",
    url: "non-vasculair/leverbiopt.html",
    trefwoorden: ["leverbiopt","biopsie","lever","HCC","hepatocellulair","metastase","cholangiocarcinoom","focale laesie","echogeleid","17G","18G","coaxiaal","steatohepatitis"] },

  { naam: "Bronchiaalarterie embolisatie", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/bae.html",
    trefwoorden: ["BAE","bronchiaalarterie","hemoptoe","embolisatie","PVA","Adamkiewicz","spinaal","bronchiëctasie","tuberculose","aspergilloom"] },
  { naam: "EVAR — Endovasculaire Aneurysma Repair", categorie: "Vasculair", subcategorie: "Arterieel", tag: "vasc",
    url: "vasculair/evar.html",
    trefwoorden: ["EVAR","aneurysma","AAA","aorta","abdominaal","stentgraft","endograft","endoleak","infrarenaal","oversizing","planning","iliacaal","bifurcatie"] },
  { naam: "Vaatchirurgie MDO bekken/beenvaten", categorie: "MDO", subcategorie: "PAV", tag: "vasc",
    url: "mdo/vaatchirurgie-mdo.html",
    trefwoorden: ["PAV","claudicatio","kritieke ischemie","TASC","Fontaine","iliacaal","femoropopliteaal","PTA","stent","bypass","ABI","DEB","CERAB","antitrombose"] },
  { naam: "Aorta MDO — aorta & iliacale aneurysmata", categorie: "MDO", subcategorie: "AAA", tag: "vasc",
    url: "mdo/aorta-mdo.html",
    trefwoorden: ["aorta","aneurysma","AAA","EVAR","endoleak","ESVS","stentgraft","iliacaal","abdominaal","ruptuur"] },
  { naam: "Visceraal MDO — mesenteriale ischemie", categorie: "MDO", subcategorie: "Mesenteriaal", tag: "vasc",
    url: "mdo/visceraal-mdo.html",
    trefwoorden: ["visceraal","mesenteriaal","ischemie","AMI","CMI","SMA","truncus coeliacus","Koelemay","CoBaGI","darmangina","stent"] },
  { naam: "Shunt MDO", categorie: "MDO", subcategorie: "Hemodialyse toegang", tag: "vasc",
    url: "mdo/shunt-mdo.html",
    trefwoorden: ["shunt","AVF","AVG","hemodialyse","MDO","fistel","RCAVF","BCAVF","basilica transpositie","duplex"] },
  { naam: "Disclaimer", categorie: "Overig", subcategorie: "Referentie", tag: "mat",
    url: "disclaimer.html",
    trefwoorden: ["disclaimer","aansprakelijkheid","voorwaarden","gebruik","validatie","richtlijn","protocol"] },
  { naam: "Miltembolisatie", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/miltembolisatie.html",
    trefwoorden: ["milt","miltembolisatie","lienalis","splenic","trauma","bloeding","AAST","coils","plug","proximaal","distaal","pseudoaneurysma","splenectomie","miltbehoud","extravasatie"] },
  { naam: "Nierembolisatie", categorie: "Vasculair", subcategorie: "Embolisatie", tag: "vasc",
    url: "vasculair/nierembolisatie.html",
    trefwoorden: ["nier","nierembolisatie","renalis","renal","trauma","bloeding","hematurie","PCNL","nierbiopt","pseudoaneurysma","AV-fistel","superselectief","microcoils","sandwichtechniek","AAST"] },
];
